### PR TITLE
Made redisio providers to correctly mark resource as changed.

### PR DESCRIPTION
**Pull request by iggyzap**
At the moment all redisio providers will send notifications that resource was changed that might result in unnecessary redis restarts.

I've removed few lines that forcibly mark resource as changed + added use_inline_resources which will rely on chef's provided resources logic to mark changed things.

There is one drawback - use_inline_resources was introduced in chef 11.

### CODE REVIEW

**Comment by brianbianco** [comment]
So redisio should actually properly send notifications.  It is using a helper command I wrote.  you can see it here.

https://github.com/brianbianco/redisio/blob/master/libraries/redisio.rb#L21

This allows it to provide notifications for versions of chef under chef 11.  I would prefer to keep that backwards compatibility.  Perhaps when the cookbook approaches version 3.0 we will drop chef10 support and start using features of chef 11+

**Comment by iggyzap** [comment]
I've modified logic to use duck-typing to verify if use_inline_resources is available + added back forced notifications in case such function is not available in chef api.

**Comment by brianbianco** [comment]
By removing the recipe_eval do block this will break the same functionality in chef 10 if I am remembering correctly.

The way the recipe eval looks is by generating a subset of resources and calling updated by last action if any of them were updated along the way, then returning to the regular set of resources after the particular block is done.

This code will indeed only call 'use inline resources' if it is available, but if it isn't available the resource will no longer be properly updated when resources inside of it are called.

It may be sufficient to use a check INSIDE of the recipe_eval to just have it no-op if 'use_inline_resources' is available instead of removing it entirely.

**Comment by Xorima** [comment]
Hi
We have just adopted this cookbook and are aiming to rebaseline it, as part of this we are closing down all prs older than 1 year.
If you still need this change please open a new PR and we will assess this as part of our rebaseline
Thanks for your understanding
Sous-Chefs

**Pull request closed without merging**
