### PR TITLE
add option to set aclfile

### PR DESCRIPTION
**Pull request by simonasr**
# Description

Adding `aclfile` option to Redis configuration file.

## Issues Resolved

Enables configuring external ACL file for Redis v6+

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by xorima** [comment]
Hey @simonasr 

Thanks for this. Can you drop an update to the change log under the ## Unreleased section then I can get this shipped asap

**Comment by simonasr** [comment]
> Hey @simonasr
> 
> Thanks for this. Can you drop an update to the change log under the ## Unreleased section then I can get this shipped asap

Thanks @xorima! Changelog updated.

**Review by xorima — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [6.6.0](https://github.com/sous-chefs/redisio/releases/tag/6.6.0)

**Comment by damacus** [comment]
@simonasr do you want to take point on removing some of the older configuration options for redis? 

Looks like we really only want to be supporting 6+ at a minimum

https://endoflife.date/redis

**Comment by simonasr** [comment]
> @simonasr do you want to take point on removing some of the older configuration options for redis?
> 
> Looks like we really only want to be supporting 6+ at a minimum
> 
> https://endoflife.date/redis

Hi @damacus 

Sure, I'd be happy to help with that in my free time. Just to be clear, are we talking about removing obsolete conditional statements from the configuration templates and related code if such, or is there more to it? As far as I know, Redis hasn't actually removed any configuration options, so I just want to understand the scope of what we're doing.

**Comment by damacus** [comment]
Yeah, pretty much want to make sure 6 and 7 work. It's easier if it's headed up by someone who still uses it

**Pull request merged**
