### PR TITLE
Require Chef 12 and other misc changes

### PR DESCRIPTION
**Pull request by tas50**
1 change per commit

### CODE REVIEW

**Comment by tas50** [comment]
Looks like I still need to convert things to cookstyle and InSpec before this one will pass

**Comment by majormoses** [comment]
@tas50 I know its been a while but any plans on picking this back up?

**Comment by tas50** [comment]
I was actually going to message you about this one. I can pick it back up after Chef 14 ships. I'm a bit swamped right now.

**Comment by majormoses** [comment]
@tas50 I got some parallel work done on my end in #375 and if looks good I will merge and release it, when you have some time you can come back and do more cleanup if you wish.

**Pull request closed without merging**
