### PR TITLE
Load modules

### PR DESCRIPTION
**Pull request by weiwu-sre**
# Description

To support load modules for Redis 4+

## Check List

- [x] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ramereth** [comment]
@weiwu-sre please include a change log entry

**Comment by weiwu-sre** [comment]
> @weiwu-sre please include a change log entry

Updated.

**Comment by ramereth** [comment]
@weiwu-sre can you please rebase and fix the mdl issue? I tried pushing with the fixes myself but I don't have permission to do that.

**Review by xorima — APPROVED** [review]

**Review by xorima — APPROVED** [review]

**Pull request closed without merging**
