### PR TITLE
look for tests in /opt/verifier on containers

### LINKED ISSUE #367: Tests not running with kitchen-dokken (including in Travis), looking in /tmp rather than /opt
Tests are not running via `kitchen verify` with kitchen-dokken (I havent tried kitchen-vagrant but i expect they work). See https://travis-ci.org/brianbianco/redisio/jobs/279583552 for an example

The issue is test-kitchen is looking in `/tmp/verifier` on the instances for tests, but everything is actually stored in `/opt` (Im not sure if this is a default with kitchen-dokken or some override in this cookbook).

`kitchen verify` debug output:

```
redisio $ bundle exec kitchen verify sentinel-ubuntu-1404 -l debug
-----> Starting Kitchen (v1.19.2)
D      Berksfile found at /Users/austinheiman/code/github.com/atheiman/redisio/Berksfile, loading Berkshelf
D      Berkshelf 6.3.1 library loaded
...
D      Berksfile found at /Users/austinheiman/code/github.com/atheiman/redisio/Berksfile, loading Berkshelf
D      Berkshelf 6.3.1 previously loaded
-----> Verifying <sentinel-ubuntu-1404>...
       Creating kitchen sandbox in /Users/austinheiman/.dokken/verifier_sandbox/9033a7797a-sentinel-ubuntu-1404
-----> Busser installation detected (busser)
-----> Busser plugin detected: busser-serverspec
-----> Running serverspec test suite
/opt/chef/embedded/bin/ruby -I/tmp/verifier/suites/serverspec -I/tmp/verifier/gems/gems/rspec-support-3.7.0/lib:/tmp/verifier/gems/gems/rspec-core-3.7.1/lib /opt/chef/embedded/bin/rspec --pattern /tmp/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /tmp/verifier/suites/serverspec
No examples found.

Finished in 0.0003 seconds (files took 0.0485 seconds to load)
0 examples, 0 failures

       Finished verifying <sentinel-ubuntu-1404> (0m0.77s).
-----> Kitchen is finished. (0m1.78s)
```

So when I run the same command on the instance manually, but use `/opt` instead of `/tmp` everywhere, it works:

```
redisio $ bundle exec kitchen login sentinel-ubuntu-1404 -l debug
D      Berksfile found at /Users/austinheiman/code/github.com/atheiman/redisio/Berksfile, loading Berkshelf
D      Berkshelf 6.3.1 library loaded
...
D      Berksfile found at /Users/austinheiman/code/github.com/atheiman/redisio/Berksfile, loading Berkshelf
D      Berkshelf 6.3.1 previously loaded
D      Login command: docker exec -it 9033a7797a-sentinel-ubuntu-1404 /bin/bash -login -i (Options: {})
root@dokken:/# /opt/chef/embedded/bin/ruby -I/opt/verifier/suites/serverspec -I/opt/verifier/gems/gems/rspec-support-3.7.0/lib:/opt/verifier/gems/gems/rspec-core-3.7.1/lib /opt/chef/embedded/bin/rspec --pattern /opt/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /opt/verifier/suites/serverspec

Redis-Sentinel
  behaves like sentinel on port
WARNING: ignoring the provided expectation message argument ({:if=>true}) since it is not a string or a proc.
    enables the redis-sentinel service
    is listening on port 26379

Finished in 0.03449 seconds (files took 0.75687 seconds to load)
2 examples, 0 failures
```

### PR DESCRIPTION
**Pull request by atheiman**
This is explained in the kitchen-dokken readme https://github.com/someara/kitchen-dokken#tmpfs-on-tmp

fixes #367

### CODE REVIEW

**Comment by atheiman** [comment]
Looks like this is working now and running tests. Here is output from [one of the jobs (`default-centos-7 `)](https://travis-ci.org/brianbianco/redisio/jobs/325260928):

```
Chef Client finished, 50/111 resources updated in 01 minutes 31 seconds
       Finished converging <default-centos-7> (1m43.19s).
-----> Setting up <default-centos-7>...
       Finished setting up <default-centos-7> (0m0.00s).
-----> Verifying <default-centos-7>...
       Creating kitchen sandbox in /home/travis/.dokken/verifier_sandbox/b52efd0ae5-default-centos-7
-----> Installing Busser (busser)
Successfully installed thor-0.19.0
Successfully installed busser-0.7.1
2 gems installed
-----> Installing Busser plugin: busser-serverspec
       Plugin serverspec installed (version 0.5.10)
-----> Running postinstall for serverspec plugin
-----> Running serverspec test suite
-----> Installing Serverspec..
-----> serverspec installed (version 2.41.3)
/opt/chef/embedded/bin/ruby -I/opt/verifier/suites/serverspec -I/opt/verifier/gems/gems/rspec-support-3.7.0/lib:/opt/verifier/gems/gems/rspec-core-3.7.1/lib /opt/chef/embedded/bin/rspec --pattern /opt/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /opt/verifier/suites/serverspec
Redis
  behaves like redis on port
WARNING: ignoring the provided expectation message argument ({:if=>true}) since it is not a string or a proc.
    enables the redis service
    is listening on port 6379
File "/etc/redis/savetest.conf"
  should be file
  content
    should match "save a"
  content
    should match "save b"
  content
    should match "save c"
Finished in 0.07877 seconds (files took 0.38577 seconds to load)
6 examples, 0 failures
       Finished verifying <default-centos-7> (0m5.09s).
-----> Kitchen is finished. (2m10.53s)
```

**Comment by atheiman** [comment]
So since these tests havent been running for a while (I have not looked back to see how long), there are a lot of failures. here is a quick breakdown of the failures by test instance name

- `default-debian-7`, `default-debian-8`, `default-ubuntu-1404`, `default-ubuntu-1604`
  ```
  1) Command "semanage fcontext --list --noheading | grep -F redis" stdout should match /^\/etc\/redis\(\/\.\*\)\?\s.*:redis_conf_t:/
     Failure/Error: its(:stdout) { should match(pattern) }
       expected "" to match /^\/etc\/redis\(\/\.\*\)\?\s.*:redis_conf_t:/
       Diff:
       @@ -1,2 +1,2 @@
       -/^\/etc\/redis\(\/\.\*\)\?\s.*:redis_conf_t:/
       +""
       /bin/sh -c semanage\ fcontext\ --list\ --noheading\ \|\ grep\ -F\ redis
       
     # /opt/verifier/suites/serverspec/redisio_spec.rb:25:in `block (3 levels) in <top (required)>'

  2) Command "semanage fcontext --list --noheading | grep -F redis" stdout should match /^\/var\/lib\/redis\(\/\.\*\)\?\s.*:redis_var_lib_t:/
     Failure/Error: its(:stdout) { should match(pattern) }
       expected "" to match /^\/var\/lib\/redis\(\/\.\*\)\?\s.*:redis_var_lib_t:/
       Diff:
       @@ -1,2 +1,2 @@
       -/^\/var\/lib\/redis\(\/\.\*\)\?\s.*:redis_var_lib_t:/
       +""
       
     # /opt/verifier/suites/serverspec/redisio_spec.rb:25:in `block (3 levels) in <top (required)>'

  3) Command "semanage fcontext --list --noheading | grep -F redis" stdout should match /^\/var\/run\/redis\(\/\.\*\)\?\s.*:redis_var_run_t:/
     Failure/Error: its(:stdout) { should match(pattern) }
       expected "" to match /^\/var\/run\/redis\(\/\.\*\)\?\s.*:redis_var_run_t:/
       Diff:
       @@ -1,2 +1,2 @@
       -/^\/var\/run\/redis\(\/\.\*\)\?\s.*:redis_var_run_t:/
       +""
       
     # /opt/verifier/suites/serverspec/redisio_spec.rb:25:in `block (3 levels) in <top (required)>'

  4) Command "semanage fcontext --list --noheading | grep -F redis" stdout should match /^\/var\/log\/redis\(\/\.\*\)\?\s.*:redis_log_t:/
     Failure/Error: its(:stdout) { should match(pattern) }
       expected "" to match /^\/var\/log\/redis\(\/\.\*\)\?\s.*:redis_log_t:/
       Diff:
       @@ -1,2 +1,2 @@
       -/^\/var\/log\/redis\(\/\.\*\)\?\s.*:redis_log_t:/
       +""
       
     # /opt/verifier/suites/serverspec/redisio_spec.rb:25:in `block (3 levels) in <top (required)>'
  ```

- `redis-package-ubuntu-1604`
  ```
  1) Redis behaves like redis on port is listening on port 6379
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected Port "6379" to be listening
       /bin/sh -c ss\ -tunl\ \|\ grep\ --\ :6379\\\ 
       
     Shared Example Group: "redis on port" called from /opt/verifier/suites/serverspec/redisio_spec.rb:4
     # /opt/verifier/suites/serverspec/redisio_examples.rb:22:in `block (2 levels) in <top (required)>'
  ```

- `sentinel-fedora-latest`
  ```
  -----> Starting Kitchen (v1.19.2)
  -----> Creating <sentinel-fedora-latest>...
         Creating container chef-12.19.36
         Creating kitchen sandbox at /home/travis/.dokken/kitchen_sandbox/b52efd0ae5-sentinel-fedora-latest
         Creating verifier sandbox at /home/travis/.dokken/verifier_sandbox/b52efd0ae5-sentinel-fedora-latest
         Building work image..
  >>>>>> ------Exception-------
  >>>>>> Class: Kitchen::ActionFailed
  >>>>>> Message: 1 actions failed.
  >>>>>>     Failed to complete #create action: [work_image build failed: The command '/bin/sh -c dnf -y install yum which systemd-sysv initscripts wget net-tools sudo' returned a non-zero code: 1. The common scenerios are incorrect intermediateinstructions such as not including `-y` on an `apt-get` or similar. The other common scenerio is a transient error such as an unresponsive mirror.] on sentinel-fedora-latest
  >>>>>> ----------------------
  ```

- `multisentinel-centos-6`, `multisentinel-centos-7`, `multisentinel-debian-7`, `multisentinel-debian-8`, `multisentinel-ubuntu-1404`, `multisentinel-ubuntu-1604`
  ```
  rspec '/opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[2:2:1]' # File "/etc/redis/sentinel_cluster.conf" content should match /sentinel down-after-milliseconds master6379 30000/
  rspec '/opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[2:3:1]' # File "/etc/redis/sentinel_cluster.conf" content should match /sentinel parallel-syncs master6379 1/
  rspec '/opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[2:4:1]' # File "/etc/redis/sentinel_cluster.conf" content should match /sentinel failover-timeout master6379 900000/
  rspec '/opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[2:6:1]' # File "/etc/redis/sentinel_cluster.conf" content should match /sentinel down-after-milliseconds master6380 30000/
  rspec '/opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[2:7:1]' # File "/etc/redis/sentinel_cluster.conf" content should match /sentinel parallel-syncs master6380 1/
  rspec '/opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[2:8:1]' # File "/etc/redis/sentinel_cluster.conf" content should match /sentinel failover-timeout master6380 900000/
  rspec '/opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[4:25:1]' # Command "/usr/local/bin/redis-cli --raw -p 26379 SENTINEL MASTER master6379" stdout should match /900000/
  rspec '/opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[5:25:1]' # Command "/usr/local/bin/redis-cli --raw -p 26379 SENTINEL MASTER master6380" stdout should match /900000/
  ```

- `multisentinel-fedora-latest`
  ```
  rspec /opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[1:1:2:1:1] # Redis-Sentinel behaves like sentinel on port Command "ps aux | grep -v grep | grep 'redis-server' | grep '*:26379'" exit_status should eq 0
  rspec /opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[2:2:1] # File "/etc/redis/sentinel_cluster.conf" content should match /sentinel down-after-milliseconds master6379 30000/
  rspec /opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[2:3:1] # File "/etc/redis/sentinel_cluster.conf" content should match /sentinel parallel-syncs master6379 1/
  rspec /opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[2:4:1] # File "/etc/redis/sentinel_cluster.conf" content should match /sentinel failover-timeout master6379 900000/
  rspec /opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[2:6:1] # File "/etc/redis/sentinel_cluster.conf" content should match /sentinel down-after-milliseconds master6380 30000/
  rspec /opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[2:7:1] # File "/etc/redis/sentinel_cluster.conf" content should match /sentinel parallel-syncs master6380 1/
  rspec /opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[2:8:1] # File "/etc/redis/sentinel_cluster.conf" content should match /sentinel failover-timeout master6380 900000/
  rspec /opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[3:25:1] # Command "/usr/local/bin/redis-cli --raw -p 26379 SENTINEL MASTER master6379" stdout should match /900000/
  rspec /opt/verifier/suites/serverspec/multiple_sentinels_spec.rb[4:25:1] # Command "/usr/local/bin/redis-cli --raw -p 26379 SENTINEL MASTER master6380" stdout should match /900000/
  ```

**Comment by majormoses** [comment]
Thanks for taking a look and fixing some of the issues. For some reason travis is not triggering a rebuild when I issue it in console. I pushed an empty commit to try to have it re-run it. I am pretty new to this cookbook so it might take me a bit to fix the tests but I'd like to postpone merging any functional changes until tests pass again. If you want to pack out everything but the dokken config I am :+1: to merge this and work on fixing tests to get this cookbook in a better place.

**Comment by atheiman** [comment]
im not sure what you want, the only changes in here are to fix most of the travis / docker tests. myabe youre referring to the rubocop.yml, but i think that thing is getting a little silly when it has exceptions for almost every rubocop style rule.

**Comment by majormoses** [comment]
I was specifically referring to the change in how we reference data bags. While I realize that is preferable to use `data_bag_item` over `Chef::EncryptedDataBagItem.load` I do consider that a functional change.

> edit: im fine with you pushing commits up to this, I dont work much with this cookbook anymore so I dont know how actively ill follow up on these prs

Sorry to hear that I will try to do what I can with the limited time I have.

**Comment by tas50** [comment]
@atheiman we've reworked the whole testing of this cookbook and brought in a few of your changes. Any change you can bring in just the verifier bit so we can get this merged in.

**Comment by Xorima** [comment]
Hi
We have just adopted this cookbook and are aiming to rebaseline it, as part of this we are closing down all prs older than 1 year.
If you still need this change please open a new PR and we will assess this as part of our rebaseline
Thanks for your understanding
Sous-Chefs

**Pull request closed without merging**
