### PR TITLE
Create pid file at systemd start

### PR DESCRIPTION
**Pull request by waltercool**
Proposal to solve https://github.com/brianbianco/redisio/issues/357

Please check if this might work under general propose. Works perfectly for me.

Because daemonize is no, Redis isn't creating a PID, so basically I'm creating a new one each time start and stop are executed, using same logic as SysVinit script.

### CODE REVIEW

**Comment by majormoses** [comment]
This seems legit, I am new to maintaining this cookbook so maybe I am missing something is there a reason we don't daemonize redis in the first place?

**Comment by waltercool** [comment]
I can't remember actually the reason, but I tested right now with redis 2.8.20 and worked fine.

Let me do some tests with a modified version of systemd and modify the pull request.

**Comment by majormoses** [comment]
@brianbianco any idea why we run it non daemonized?

**Comment by brianbianco** [comment]
No clue, pretty sure this was an accepted PR from an outside contributor.

**Comment by josephholsten** [comment]
BTW, I've never actually needed a "real" PID file with systemd, you can do something like:
```
PID=$(systemctl show -p MainPID smartd.service 2>/dev/null | cut -d= -f2)
```

per [systemctl(1)](https://www.freedesktop.org/software/systemd/man/systemctl.html)

Or if you want it within `ExecReload=` you can access it with `$MAINPID` per [systemd.service(5)](https://www.freedesktop.org/software/systemd/man/systemd.service.html)

**Comment by brianbianco** [comment]
This PR is out of date with the base branch.  It seems like this should be merged otherwise.

**Comment by waltercool** [comment]
I'm no longer owner of the repository, shall I reopen a new PR with the repository updated?

**Comment by Xorima** [comment]
Hi
We have just adopted this cookbook and are aiming to rebaseline it, as part of this we are closing down all prs older than 1 year.
If you still need this change please open a new PR and we will assess this as part of our rebaseline
Thanks for your understanding
Sous-Chefs

**Comment by waltercool** [comment]
Makes sense, thanks!

**Pull request closed without merging**
