### PR TITLE
Add includes option to sentinel config file

### PR DESCRIPTION
**Pull request by zygisa**
# Description

Add `includes` option to Sentinel configuration file.

## Issues Resolved

Currently, there's no way to include custom config files into Sentinel config. 

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Review by xorima — CHANGES_REQUESTED** [review]
Can we get a test added for this change please?

**Comment by zygisa** [comment]
> Can we get a test added for this change please?

Sure thing! Any suggestions on how to implement this? As far as I can see there are currently no config file related tests in [sentinel](https://github.com/sous-chefs/redisio/blob/main/test/integration/sentinel/serverspec/sentinel_spec.rb) suite.

**Comment by zygisa** [comment]
On further inspection, it seems that the integration tests are not even being executed properly since the [verifier in kitchen.yml is set to inspec](https://github.com/sous-chefs/redisio/blob/main/kitchen.yml#L15) however all the tests are written for `serverspec` (unless I'm missing something obvious here). If I check the log of any integration test in this PR (for example [this one](https://github.com/sous-chefs/redisio/actions/runs/7423572556/job/20201319410?pr=491#step:4:2239)) I see that no tests are executed:
```shell
-----> Verifying <multisentinel-rockylinux-8>...
       Detected alternative framework tests for `serverspec`

Test Summary: 0 successful, 0 failures, 0 skipped
       Finished verifying <multisentinel-rockylinux-8> (0m2.74s).
```
@damacus @xorima any suggestions on how to proceed with this one? 🙏

**Comment by damacus** [comment]
Been thinking about this one. 


Are you able to converge an instance and check the config manually this time.

We should get the tests fixed up in the next iteration.

**Comment by zygisa** [comment]
> Been thinking about this one.
> 
> Are you able to converge an instance and check the config manually this time.
> 
> We should get the tests fixed up in the next iteration.

Yeah, I've tested locally and have some functionality built around this feature already. Conducted a quick test now - updated `multisentinel` test suite to look like this: 
```yaml
  - name: multisentinel
    run_list:
      - recipe[redisio::default]
      - recipe[redisio::enable]
      - recipe[redisio::sentinel]
      - recipe[redisio::sentinel_enable]
    attributes:
      redisio:
        servers:
          - port: 6379
          - port: 6380
        sentinels:
          -
            name: 'cluster'
            sentinel_bind: 0.0.0.0
            sentinel_port: 26379
            includes: ['/etc/redis/test.conf']
            masters:
              -
                name: 'sentinel6379'
                master_name: 'master6379'
                master_ip: '127.0.0.1'
                master_port: 6379
              -
                name: 'sentinel6380'
                master_name: 'master6380'
                master_ip: '127.0.0.1'
                master_port: 6380
```

Sentinel config looks like this after converge:
```shell
[root@dokken /]# cat /etc/redis/sentinel_cluster.conf | tail -n 10
################################## INCLUDES ###################################

# Include one or more other config files here.  This is useful if you
# have a standard template that goes to all redis server but also need
# to customize a few per-server settings.  Include files can include
# other files, so use this wisely.
#
# include /path/to/local.conf
# include /path/to/other.conf
    include /etc/redis/test.conf
```

**Review by xorima — APPROVED** [review]

**Comment by zygisa** [comment]
hey @damacus, can we get this merged and released, please? Thanks!

**Comment by zygisa** [comment]
@damacus @xorima sorry for another ping but I'd really appreciate if this could get merged today. We have a functionality we want to release that depends on this feature. Thanks! 🙏

**Comment by kitchen-porter** [comment]
Released as: [6.7.1](https://github.com/sous-chefs/redisio/releases/tag/6.7.1)

**Pull request merged**
