### PR TITLE
Fix configdir permissions (part 2)

### PR DESCRIPTION
**Pull request by simonasr**
# Description

Looks like this was missed in https://github.com/sous-chefs/redisio/pull/451
Adding same fix to `providers/sentinel.rb`

## Issues Resolved

- https://github.com/sous-chefs/redisio/issues/450

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Review by damacus — APPROVED** [review]
Awesome! Thanks for fixing this.

**Comment by damacus** [comment]
Argh, looks like we also need to fix this SElinux cookbook error


```ruby
include SELinux::Cookbook::StateHelpers
```

**Comment by simonasr** [comment]
> Argh, looks like we also need to fix this SElinux cookbook error
> 
> ```ruby
> include SELinux::Cookbook::StateHelpers
> ```

Yes, looks unrelated to this pr 🤔

**Comment by damacus** [comment]
Yeah it definitely is. It's one of those. Make a PR, find breakages in upstream.

**Comment by kitchen-porter** [comment]
Released as: [6.2.1](https://github.com/sous-chefs/redisio/releases/tag/6.2.1)

**Pull request merged**
