### PR TITLE
Make the redisio `configure` resource idempotent

### LINKED ISSUE #215: redisio_configure not idempotent
rediso_configure lwrp is not idempotent. Below is the output of kitchen converge after an initial converge of the test suite `default`. 

```
 -----> Converging <default-centos>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       Transferring files to <default-centos>
       Starting Chef Client, version 12.2.1
       [2015-07-16T18:44:33+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["redisio::default", "redisio::enable"]
       Synchronizing Cookbooks:
         - ulimit
         - redisio
         - build-essential

       Converging 16 resources
       Recipe: redisio::_install_prereqs
        (up to date)
       Recipe: build-essential::_rhel
         * yum_package[autoconf] action install (up to date)
         * yum_package[bison] action install (up to date)
         * yum_package[flex] action install (up to date)
         * yum_package[gcc] action install (up to date)
         * yum_package[gcc-c++] action install (up to date)
         * yum_package[kernel-devel] action install (up to date)
         * yum_package[make] action install (up to date)
         * yum_package[m4] action install (up to date)
         * yum_package[patch] action install (up to date)
       Recipe: redisio::install
         * redisio_install[redis-installation] action run

       Recipe: redisio::configure
         * redisio_configure[redis-servers] action run
        (skipped due to not_if)
           * directory[/etc/redis] action create (up to date)
           * directory[/var/lib/redis] action create (up to date)
           * directory[/var/run/redis/6379] action create (up to date)
           * file[/var/lib/redis/appendonly-6379.aof] action create (skipped due to only_if)
           * file[/var/lib/redis/dump-6379.rdb] action create (skipped due to only_if)
         Recipe: <Dynamically Defined Resource>
           * template[/etc/security/limits.d/redis_limits.conf] action create (up to date)
           * template[/etc/redis/6379.conf] action create (up to date)
           * template[/etc/init.d/redis6379] action create (up to date)
           * template[/etc/init/redis6379.conf] action create (skipped due to only_if)
           - evaluate block and run any associated actions[2015-07-16T18:44:34+00:00] WARN: savetest: given a save argument as a string, instead of an array.
       [2015-07-16T18:44:34+00:00] WARN: savetest: This will be deprecated in future versions of the redisio cookbook.

           * user[redis] action create (skipped due to not_if)
           * directory[/etc/redis] action create (up to date)
           * directory[/var/lib/redis] action create (up to date)
           * directory[/var/run/redis/savetest] action create (up to date)
           * file[/var/lib/redis/appendonly-savetest.aof] action create (skipped due to only_if)
           * file[/var/lib/redis/dump-savetest.rdb] action create (skipped due to only_if)
           * template[/etc/security/limits.d/redis_limits.conf] action create (up to date)
           * template[/etc/redis/savetest.conf] action create (up to date)
           * template[/etc/init.d/redissavetest] action create (up to date)
           * template[/etc/init/redissavetest.conf] action create (skipped due to only_if)
           - evaluate block and run any associated actions
       Recipe: redisio::configure
         * template[/usr/lib/systemd/system/redis@.service] action create (skipped due to only_if)
         * service[redis6379] action nothing (skipped due to action :nothing)
         * service[redis6379] action start (up to date)
         * service[redis6379] action enable (up to date)
         * service[redissavetest] action nothing (skipped due to action :nothing)
        (up to date)
         * service[redissavetest] action enable (up to date)
       Recipe: redisio::enable
         * execute[reload-systemd] action nothing (skipped due to action :nothing)

       Running handlers:
       Running handlers complete
       Chef Client finished, 2/28 resources updated in 2.490925811 seconds
       Finished converging <default-centos> (0m10.52s).
```

I have a chef handler set up to collect all the updated resources after a converge. 

``` ruby
  class UpdatedResources < Chef::Handler
    def report
      File.open('/tmp/handler_output', 'w+') do |file|
        file.write("#{run_status.updated_resources.size} \
          resources updated this run:\n")
        run_status.updated_resources.each do |r|
          file.write("Updated resource: #{r}\n")
        end
      end
    end
  end
```

And the output of the my handler is as follows. redisio_configure is updated. (redisio_install also has the same problem, but here I'm just focusing on redisio_configure lwrp)

```
3           resources updated this run:
Updated resource: redisio_install[redis-installation]
Updated resource: redisio_configure[redis-servers]
Updated resource: chef_handler[OtppChefHelpers::UpdatedResources]
```

So I took a look the the redisio_configure provider: 

``` ruby
action :run do
  configure
  new_resource.updated_by_last_action(true)
end
```

and found the below line of code problematic. new_resource.updated_by_last_action() should not be hardcoded to true.

```
new_resource.updated_by_last_action(true)
```

The problem we encountered is that configuration changes do not notify redis service restart. There is no way to pick up config changes except to manually write a service resource block that performs stop and start actions. 
https://github.com/brianbianco/redisio/issues/44  This issue touches on the problem of services not notified when config changes. I appreciate that the `subscribe` option in chef solves this problem. However, my question is that if the subscribed resource is updated all the time, as in this case with `redisio_configure`, then there is no difference between the `subscribe` option and the option to perform manual restart on each and every converge.

### PR DESCRIPTION
**Pull request by aae42**
# Description

Makes the redisio `configure` resource idempotent.

It's helpful to hide whitespace when reviewing diffs.

## Issues Resolved

#215 

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by aae42** [comment]
could add a config to the `.kitchen.yml` to make the log file touch thing easier to see, but neither that, or the lack of idempotency on the configure resource is going to be noticed unless we do multiple converges and enforce idempotency in the provisioner

**Comment by ramereth** [comment]
@aae42 looks like we need to clean up the CI environment. Let me do that in another PR so that this can be properly tested.

**Comment by aae42** [comment]
@ramereth want to take another look?

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [6.4.0](https://github.com/sous-chefs/redisio/releases/tag/6.4.0)

**Pull request merged**
