### PR TITLE
cleanup: remove support for EOL Redis versions

### PR DESCRIPTION
**Pull request by simonasr**
# Description

This PR updates Redis configuration to be compatible with version post to v6, following th end-of-life for older versions.
Redis EOL: https://endoflife.date/redis
Related discussion: https://github.com/sous-chefs/redisio/pull/485#issuecomment-1806862360

## Issues Resolved

- [x] Remove obsolete Redis version checks
- [x] Remove deprecated Redis configuration options
- [x] Update Redis docs in configuration template
- [x] Update `slave -> replica` where applicable
- [x] Remove `redis-package` test suite
- [x] Bump Redis version used for tests 
- [x] Update CHANGELOG

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by xorima** [comment]
Adding major as release version as we are removing stuff and version numbers are free.

**Comment by simonasr** [comment]
Hi @damacus, i'm a bit stuck here:
- most Linux distributions provide Redis v4 package only, which does not work with "modern" Redis configurations. How could we proceed here - should we remove "redis-package" test suite from integration tests? 🤔

**Comment by damacus** [comment]
Yeah just remove the package test here 

According to https://endoflife.date/redis we should only be testing 6.3, 7.0 and 7.2. Anything else isn't getting patched

**Comment by damacus** [comment]
Not for this cleanup PR, but it's easier to split out the documentation for each of the resources into their own file a la, java/apache2.

**Comment by simonasr** [comment]
Hi @damacus 
I've finalised the PR and believe it's now ready for review. Finding time to dedicate to this was more challenging than I initially thought. Could you please review it and share your feedback? Additionally, if further modifications or steps are needed, please guide me on how to proceed.

**Review by xorima — COMMENTED** [review]
Not a blocker but do we need an upgrading guideline for this? 
I.e you have today you need tomorrow kinda things

**Comment by simonasr** [comment]
> Not a blocker but do we need an upgrading guideline for this? I.e you have today you need tomorrow kinda things

Thanks @xorima, do you have in mind something like example bellow? 🤔 should this go to the CHANGELOG?

> Upgrade Guidelines:
>
> - Ensure all Redis instances are upgraded to version 6.2.14 or higher.
> - Update configuration files to reflect the terminology change from "slave" to "replica."
> - Remove any references to deprecated options like `list-max-ziplist-entries` and `list-max-ziplist-value`.
> - Test the compatibility of your Chef cookbook with Redis v6+ before deploying the upgrade.

**Review by xorima — APPROVED** [review]

**Comment by xorima** [comment]
I'm happy, but would like further review from @damacus  or @ramereth  ideally

sorry for missing your message @simonasr , the last few weeks have been full on.

**Review by damacus — APPROVED** [review]
🚢

**Comment by kitchen-porter** [comment]
Released as: [7.0.0](https://github.com/sous-chefs/redisio/releases/tag/7.0.0)

**Comment by xorima** [comment]
Shipped, sorry about that, our release system had a bad day ...

**Pull request merged**
